name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile English
        uses: xu-cheng/latex-action@v2
        with:
          root_file: software-engineer/english.tex
      - name: Compile Swedish
        uses: xu-cheng/latex-action@v2
        with:
          root_file: software-engineer/swedish.tex
